### ISSUE TITLE
Blurry dropdowns on Chrome

### ISSUE THREAD

**Issue by lucasriondel** [ckeditor/ckeditor5#1053]
🐞 Bug report  
CKEditor 5

Dropdowns menus appear blurry on chrome : 

https://i.imgur.com/VVC5n9R.png

See the same on firefox : 

https://i.imgur.com/OGKVFL3.png

This can apparently be fixed if you follow the instructions on this Stack Overflow post: https://stackoverflow.com/questions/27385126/chrome-font-appears-blurry

---

If you'd like to see this fixed sooner, add 👍 to this post.

**Comment by Reinmar** [comment]
You posted wrong links, I think. Could you fix them?

Also: what OS do you use?

**Comment by lucasriondel** [comment]
Sorry about the links. I am using Windows 10 Pro, version 1803.

**Comment by Reinmar** [comment]
Are these CKEditor 5 drop downs? If so, you changed their styling completely. Can you reproduce any issues with the default styling?

**Comment by lucasriondel** [comment]
Yes, these are from CKE5, and I've changed their styles. but the blurry effect was here before, changing the style is not the cause.

**Comment by Reinmar** [comment]
cc @dkonopka @Mgsy could you confirm that dropdowns are blurry on Windows? Maybe this is OS specific because for me they look good (on macOS).

**Comment by Mgsy** [comment]
>@Mgsy could you confirm that dropdowns are blurry on Windows?

I've checked it on Windows 10, v.1803 with Chrome 67.0.3396.79 and the dropdowns display properly. The same on macOS.

![image](https://user-images.githubusercontent.com/20988892/41221434-6b1434ae-6d64-11e8-892d-ed4091da24d3.png)

**Comment by Reinmar** [comment]
@lucasriondel, could you perhaps create a JSFiddle that would show this issue?

**Comment by dkonopka** [comment]
By default we are using [translate3d hack](https://github.com/ckeditor/ckeditor5-ui/blob/master/theme/components/dropdown/dropdown.css#L42) to prevent situations like blurred fonts, so everything should be ok - maybe try to change font and check if still is blurred? 

Additionally, I can't reproduce this issue too.

**Comment by lucasriondel** [comment]
without my styles applied : https://i.imgur.com/mfShAl9.png

**Comment by lucasriondel** [comment]
also happens on the tooltip : https://i.imgur.com/KmPcjoC.png

**Comment by Reinmar** [comment]
The same as here: https://github.com/ckeditor/ckeditor5/issues/1049#issuecomment-396260680. To be able to help you we need to be able to see the issue. A demo is a must-have in such a case.

**Comment by lucasriondel** [comment]
On the issue you've referenced : i don't have the issue. On my original project, my editor is inside a modal, I think that must be the reason. I'll investigate.

**Comment by lucasriondel** [comment]
Ok, the reason it's blurry is because my modal (which host the editor) is transformed by a translate. nested transforms are not giving the good behavior on CKEditor, which displays my dropdown blurry.

**Comment by yuanyesong** [comment]
Same issure:
Dropdowns on Edge looks clearer than on Chrome

OS: Windows 10 1903
Chrome: 76.0.3809.132 x64

screenshot of CKEditor5 offical demo
Edge
![edge](https://user-images.githubusercontent.com/7038265/66213714-ea5dca00-e6f2-11e9-93b2-8124156e0119.png)

Chrome
![chrome](https://user-images.githubusercontent.com/7038265/66213723-ef227e00-e6f2-11e9-9b56-7cc1f32ed014.png)

**Comment by dkrahn** [comment]
Same here print taken from live CK Demo
![image](https://user-images.githubusercontent.com/1211686/66232857-3ba09600-e6c0-11e9-986b-37f358aefcf5.png)

It has something to do with the CSS transform. To me it becomes more visible when I toggle the responsive device option in chrome dev(might help to reproduce).
```
.ck.ck-dropdown .ck-dropdown__panel.ck-dropdown__panel_se, .ck.ck-dropdown .ck-dropdown__panel.ck-dropdown__panel_sw {
    transform: translate3d(0,100%,0);
```
Apparently changing to this fixes the issue(solution from https://stackoverflow.com/questions/27385126/chrome-font-appears-blurry):
```
.ck.ck-dropdown .ck-dropdown__panel.ck-dropdown__panel_se, .ck.ck-dropdown .ck-dropdown__panel.ck-dropdown__panel_sw {
    transform: translateY(calc(100% - .5px));
```

**Comment by yuanyesong** [comment]
> Same here print taken from live CK Demo
> ![image](https://user-images.githubusercontent.com/1211686/66232857-3ba09600-e6c0-11e9-986b-37f358aefcf5.png)
> 
> It has something to do with the CSS transform. To me it becomes more visible when I toggle the responsive device option in chrome dev(might help to reproduce).
> 
> ```
> .ck.ck-dropdown .ck-dropdown__panel.ck-dropdown__panel_se, .ck.ck-dropdown .ck-dropdown__panel.ck-dropdown__panel_sw {
>     transform: translate3d(0,100%,0);
> ```
> 
> Apparently changing to this fixes the issue(solution from https://stackoverflow.com/questions/27385126/chrome-font-appears-blurry):
> 
> ```
> .ck.ck-dropdown .ck-dropdown__panel.ck-dropdown__panel_se, .ck.ck-dropdown .ck-dropdown__panel.ck-dropdown__panel_sw {
>     transform: translateY(calc(100% - .5px));
> ```

👍Much better! but issure still exists. Appearance is different from Edge.

**Comment by 7iomka** [comment]
same issue. Hacks not resolve blurry in chrome (I'm from Mac Os)

**Comment by 7iomka** [comment]
I fixed the issue - make backface visibility to be hidden on inner dropdown panel elements:
```
.ck.ck-dropdown .ck-dropdown__panel.ck-dropdown__panel_se > *,
	.ck.ck-dropdown .ck-dropdown__panel.ck-dropdown__panel_sw > *{
		-webkit-backface-visibility: hidden;
backface-visibility: hidden;
	}
```

**Comment by Reinmar** [comment]
Thanks for the research! We'll try to include this change in the upcoming release. 

If it works for those of you who stumbled upon this issue, please add e.g. 👍 to @7iomka's comment. It's always easier for us to merge a change which is confirmed to be good by more people :)

**Comment by oleq** [comment]
Related https://github.com/ckeditor/ckeditor5/issues/2059.

**Comment by Kepro** [comment]
very old known issue with transform: translate3d(0,100%,0); ... not sure why they are not using just top: 100% instead of translate3d... and still not fixed

**Comment by mlewand** [comment]
#2059 marked as a duplicate of this issue.

**Comment by jodator** [comment]
@dkonopka & @oleq for me changing only this change in the dropdown panel CSS works:

https://github.com/ckeditor/ckeditor5-ui/blob/ffec16ab9ec48edd68a076c69c646a2a5a9a7b0a/theme/components/dropdown/dropdown.css#L50:

```css
		&.ck-dropdown__panel_se,
		&.ck-dropdown__panel_sw {
			top: 100%;
			bottom: auto;
		}
```

ps.: also I've remove the `will-change` for that. The `backface-visibility` wasn't working for me.

I've found [this](https://www.paulirish.com/2012/why-moving-elements-with-translate-is-better-than-posabs-topleft/) that speask against using `absolute / top` in favor of `translate3d` but ATM it gives blurry dropdowns :(

**Comment by oleq** [comment]
@jodator LGTM. But first, let's make sure that by removing `will-change` we don't cause a regression in https://github.com/ckeditor/ckeditor5/issues/668. Can you check this out?

**Comment by jodator** [comment]
@oleq: This is how this looks:

on the `i/1053` branch:

![Selection_020](https://user-images.githubusercontent.com/247363/68146375-25dcf580-ff38-11e9-94bb-8321689d1803.png)

on `master` branch:

![Selection_021](https://user-images.githubusercontent.com/247363/68146366-237a9b80-ff38-11e9-9e0a-5cbdd20c37bd.png)

And alignment (the one from #668): 

on the `i/1053` branch:

![Selection_023](https://user-images.githubusercontent.com/247363/68146535-82d8ab80-ff38-11e9-991b-6906dafe8b33.png)

on `master` branch:
![Selection_022](https://user-images.githubusercontent.com/247363/68146546-879d5f80-ff38-11e9-83ba-5db6a4b65a6a.png)

**Comment by Reinmar** [comment]
I confirmed @jodator's results. Also, I didn't spot any issues on Safari. Let's merge this change so we can live with it for a longer time before releasing it.

**Comment by Reinmar** [comment]
Thank you all for the feedback!
