### ISSUE TITLE
The color picker loses focus during picking font color.

### ISSUE THREAD

**Issue by gorzelinski** [ckeditor/ckeditor5#14119]
## 📝 Provide detailed reproduction steps (if any)

1. Select a word
2. Move the color picker pointer
3. Accept

https://github.com/ckeditor/ckeditor5/assets/26603574/ed8d981d-527d-4209-ab20-e84dfab4449d

### ✔️ Expected resultlt

Focus persists, and color changes the first time. 

### ❌ Actual result

What's interesting is the color changes, but the second time, when there is "document color."

## 📃 Other details

* Browser: Safari 16.4
* OS: MacOS Ventura 13.3.1

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by gorzelinski** [comment]
The issue is probably related to: https://github.com/cksource/ckeditor5-internal/issues/3268

**Comment by mlewand** [comment]
@gorzelinski have you checked it on latest `release`? Seems like something that might get fixed with #14111 

Also there's another (unmerged PR) that could affect it: #14116

**Comment by Dumluregn** [comment]
#14111 can't affect it as it only changes the behaviour for iOS (using `env.isiOS` helper) and this issue is reported for desktop Safari. I hope #14116 fixes it though.

**Comment by Dumluregn** [comment]
Important note: it only happens if you drag the slider and right after it was opened - if it's just clicked, it works as expected:

![](https://github.com/ckeditor/ckeditor5/assets/10883184/4a9becff-ab58-4a05-a246-9a495c7c55cd)

**Comment by gorzelinski** [comment]
I checked the latest release and the unmerged PR. It seems that in both cases, the issue persists.

**Comment by Dumluregn** [comment]
Yeah, unfortunately. But I'm creating a PR right now that should _definitely_ fix it.

**Comment by gorzelinski** [comment]
Perfect! 🚀

**Comment by Dumluregn** [comment]
Could you verify if it's still present at https://github.com/ckeditor/ckeditor5/pull/14127?

**Comment by gorzelinski** [comment]
The PR: https://github.com/ckeditor/ckeditor5/pull/14127 closed this issue.
