### ISSUE TITLE
Spell check support

### ISSUE THREAD

**Issue by Elbek97** [ckeditor/ckeditor5#1458]
🆕 Feature request 

## 💻 CKEditor 5

I appreciate CKEditor 5. But i have hard time to implement spell check engine to editor. 
My Spellcheck backend service is ready. 
Can you give me some hints to apply to CKEditor 5.

**Comment by oleq** [comment]
Hi, you should probably get familiar with the [Markers](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_markercollection-Marker.html#) API like [`addMarker()`](https://ckeditor.com/docs/ckeditor5/latest/api/module_engine_model_writer-Writer.html#function-addMarker). Other than that, I'm not able to help your more because there's no such feature on our side at this moment.

**Comment by wwalc** [comment]
Just one additional comment for anyone looking for an external spell checker instead of using just the one that is built-in in web browsers. We are going to offer an official spell checker for CKEditor 5 very soon, with the help of our friends from https://webspellchecker.com. The solution will contain:
 * The spell checker for 16 languages (with the possibility of supporting 142 additional languages).
 * The grammar checker for 14 languages.
 * Support for custom dictionaries.

Feel free to [contact us](https://ckeditor.com/contact/) for more details.

**Comment by Reinmar** [comment]
To add to @oleq's answer – markers are a low-level API which indeed allows rendering squiggles quite easily. We're considering implementing a higher-level API for annotations based on markers, but there's nothing concrete yet. It would make implementing a custom solution much easier.

**Comment by wsc-julia-shaptala** [comment]
@oleq, we have already implemented a solution, WProofreader, for spelling and grammar check that you can try. Here you can find a demo of [WProofreader for CKEditor 5](https://webspellchecker.com/wsc-proofreader/#proofreader-ckeditor5).

**Comment by uberism** [comment]
Does anybody have a spell checking solution for iOS?
CKEditor5 doesn't seem to play nicely with iOS keyboard and breaks autocomplete

**Comment by Reinmar** [comment]
> CKEditor5 doesn't seem to play nicely with iOS keyboard and breaks autocomplete

Could you report a separate ticket for this and describe some of the issues that you encountered? It will help us prioritising and fixing them.

**Comment by wsc-julia-shaptala** [comment]
> Does anybody have a spell checking solution for iOS?

@uberism, you can try [WProofreader for CKEditor 5](https://demo.webspellchecker.net/wsc-proofreader-ckeditor5/). It provides support for touch devices.

Here you can find a [screenshot](http://screenshots.webspellchecker.net/Monosnap_2019-03-14_16-09-27.png) from Iphone.

**Comment by uberism** [comment]
Thanks for the suggestion @wsc-julia-shaptala. Though the backspacing is still an issue with regards to how ckeditor handles text and there is no autocaptilization on new lines which makes still hesitant on continuing to use CkEditor5

**Comment by KirankumarAmbati** [comment]
(Sorry that I'm commenting on a closed issue)

@wwalc, is the CKEditor5 integrated with a spell checker ?

If not, may I know in which release/ by when it is expected to be available to the end user ? Thanks!

**Comment by AnnaTomanek** [comment]
[WProofreader for CKEditor 5](https://demo.webspellchecker.net/wsc-proofreader-ckeditor5/) is the official integration that is available and works. We are now working on the official CKEditor 5 documentation and samples for it. The resources should be ready next week.

**Comment by KirankumarAmbati** [comment]
Thanks @AnnaTomanek for the update! :)

**Comment by sravanrkumar** [comment]
**while I am trying to install webspellchecker in angular 8 .i got below issue .somebody help me to resolve it.**
D:\xampp\htdocs\shield-insurance\trunk\shield-web>  npm install --save @**webspellchecker/wproofreader-ckeditor5**
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @angular/animations@8.2.14
npm ERR! Found: @angular/core@8.2.5
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"^8.0.0 || ^9.0.0-0" from @angular/cdk@8.2.3
npm ERR!   node_modules/@angular/cdk
npm ERR!     peer @angular/cdk@"8.2.3" from @angular/material@8.2.3
npm ERR!     node_modules/@angular/material
npm ERR!       @angular/material@"^8.2.2" from the root project
npm ERR!     @angular/cdk@"~8.2.2" from the root project
npm ERR!   peer @angular/core@"8.2.5" from @angular/common@8.2.5
npm ERR!   node_modules/@angular/common
npm ERR!     peer @angular/common@"^8.0.0 || ^9.0.0-0" from @angular/cdk@8.2.3
npm ERR!     node_modules/@angular/cdk
npm ERR!       peer @angular/cdk@"8.2.3" from @angular/material@8.2.3
npm ERR!       node_modules/@angular/material
npm ERR!         @angular/material@"^8.2.2" from the root project
npm ERR!       1 more (the root project)
npm ERR!     peer @angular/common@">=6.0.0 <9 || ^9.0.0-0" from @angular/fire@5.4.2
npm ERR!     node_modules/@angular/fire
npm ERR!       @angular/fire@"5.4.2" from angularfire2@5.4.2
npm ERR!       node_modules/angularfire2
npm ERR!         angularfire2@"^5.2.3" from the root project
npm ERR!     9 more (@angular/material, @ckeditor/ckeditor5-angular, ...)
npm ERR!   10 more (@angular/fire, @angular/material, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"8.2.14" from @angular/animations@8.2.14
npm ERR! node_modules/@angular/animations
npm ERR!   peer @angular/animations@"^8.0.0 || ^9.0.0-0" from @angular/material@8.2.3
npm ERR!   node_modules/@angular/material
npm ERR!     @angular/material@"^8.2.2" from the root project
npm ERR!   @angular/animations@"^8.2.14" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/core@8.2.14
npm ERR! node_modules/@angular/core
npm ERR!   peer @angular/core@"8.2.14" from @angular/animations@8.2.14
npm ERR!   node_modules/@angular/animations
npm ERR!     peer @angular/animations@"^8.0.0 || ^9.0.0-0" from @angular/material@8.2.3
npm ERR!     node_modules/@angular/material
npm ERR!       @angular/material@"^8.2.2" from the root project
npm ERR!     @angular/animations@"^8.2.14" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\ADMIN\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ADMIN\AppData\Local\npm-cache\_logs\2022-11-10T07_51_54_328Z-debug-0.log

**Comment by PavlenkoNadya** [comment]
Hello @sravanrkumar,

I am sorry that you have obstacles to installing the WProofreader plugin using Angular 8 and truly hope that you will manage the case shortly.

The WebSpellChecker team reviewed the provided information and we suppose that the problem in the Angular dependencies is not related to the WProofreader plugin for CKEditor 5 while installing a plugin uncovered the already existing problem. If you have the other opinion please provide more information and WProfreader's role in the case.

**Comment by sravanrkumar** [comment]
Okay

________________________________
