### ISSUE TITLE
Allow inserting images via URL

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5#5161]
The current (official) UI doesn't provide a way to insert an image via an URL. We've got a [guide how to write a plugin which allows inserting an image via URL](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/quick-start.html) but no official way for doing this.

We discussed in the past how the UI of an "insert via URL or upload image" could look like in https://github.com/ckeditor/ckeditor5-image/issues/16.

---

If you'd like to see this feature implemented, please react with 👍 to this ticket.

**Comment by piotr-mamenas** [comment]
Hey, so when is this functionality going to be available in Angular?

**Comment by HassanHashemi** [comment]
Is this going to be implemented any time soon?
@Reinmar I was wondering if this release is aligned with out project time line.

**Comment by farid78epc** [comment]
.

**Comment by GhosTzz** [comment]
would be great to have this!

**Comment by Reinmar** [comment]
I've just merged a guide describing how to enable this feature :) The release is planned next week.

![](https://user-images.githubusercontent.com/156149/90831376-d9866900-e343-11ea-8aed-41fbdc236fcb.png)

**Comment by dzpt** [comment]
@Reinmar have you released it?

**Comment by justlester** [comment]
Hi, I tried the feature based on the documentation,
https://ckeditor.com/docs/ckeditor5/latest/features/image.html#inserting-images-via-source-url

but it seems that the image package is not yet updated. 

![image](https://user-images.githubusercontent.com/47380149/92077122-60305100-edee-11ea-843f-7fe064852340.png)

**Comment by mi1971** [comment]
Same issue running ckeditor5@22.0.0. Release notes seem to indicate it should be there

**Comment by josephj** [comment]
@Reinmar I have upgraded to `34.0.0` and it seems the issue is still there. There is no way to simply enable the insert image by URL without having the `ImageUpload`. 

![image](https://user-images.githubusercontent.com/136648/168517101-b24838e6-368d-4a7d-9421-4f609ee3b432.png)

The custom  https://github.com/Aeness/ckeditor5-insert-image plugin is exactly what we need, but both its licence and version stop us to use it 😫.
