### ISSUE TITLE
Tooltips / floating windows cause horizontal scrollbar on desktop at small sizes

### ISSUE THREAD

**Issue by wosevision** [ckeditor/ckeditor5#7327]
## 📝 Provide detailed reproduction steps (if any)

1. Go to the [CKEditor 5 demo page](https://ckeditor.com/ckeditor-5/demo/)
2. Resize your window to less than ~700px wide (_without_ using the devtools "responsive"/"mobile" viewer; just a regular resize)
3. Observe horizontal scrollbar

### ✔️ Expected result

There should be no horizontal scrollbar when the page is resized to less than 700px on desktop, the same as it is on a "true" mobile environments (incl. i.e. Chrome devtools)

### ❌ Actual result

A regular page resize causes a horizontal scrollbar, whereas a resize using mobile devtools does not.

## 📃 Other details

* Browser: Tested on both Chrome and Firefox
* OS: MacOS
* CKEditor version: 5
* Installed CKEditor plugins: None

From what I can see in my inspector, it's "floating" elements that seem to cause this – toolbars/tooltips/menus that are normally hidden but are showing up in the layout anyway.

**Edit:** This also happens when putting CKeditor in thin containers that butt up against page sides, which is (I think) a perfectly valid use that covers more than just "developers who resize their windows constantly".

---

<img width="698" alt="Screen Shot 2020-05-28 at 10 38 50 AM" src="https://user-images.githubusercontent.com/10436894/83155904-bc892380-a0cf-11ea-862d-d51578aee556.png">

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by FilipTokarski** [comment]
cc @oleq

**Comment by oleq** [comment]
I reproduced the issue. It is caused by the tooltips that have `position: absolute`. Unfortunately, there's no silver bullet for this problem. This is how CSS works and you can [learn more about on SO](https://stackoverflow.com/questions/36531708/why-does-position-absolute-make-page-to-overflow).

---

I decided to mitigate the problem. I implemented another position for the grouped items drop-down tooltip (the code is below) so instead of 

![](https://user-images.githubusercontent.com/1099479/83408183-81aa2700-a412-11ea-852f-7d8a443f8d23.png)

the tooltip is displayed in a slightly better way which does not cause the overflow/scrollbar

![](https://user-images.githubusercontent.com/1099479/83408243-98507e00-a412-11ea-8388-dab5d8efd625.png)

and it actually works fine. The problem is this would address only some cases. There are others where the overflow/scroll still happens, for instance:

![](https://user-images.githubusercontent.com/1099479/83408503-009f5f80-a413-11ea-8dc5-8162b2eb26a3.png)

or:

![](https://user-images.githubusercontent.com/1099479/83408525-085f0400-a413-11ea-9477-074a205a34ff.png)

And these are way more complex:

*   Features register their buttons in the component factory and they set the position of the tooltip for each button/drop–down. The `ToolbarView` knows nothing about it (but probably should).
*   To address these 2 cases above, the `ToolbarView` would need to analyze the position of an item (Is an item a first/last-child? + Is there a grouped items dropdown in the toolbar?) and set the correct position of the tooltip using the existing observable property/binding (e.g. \`TooltipView#position = 'custom'\`).
    *   That is a potential breaking change. We don't know which positions developers use and how to manage them. We implemented [`TooltipView#position`](https://ckeditor.com/docs/ckeditor5/latest/api/module_ui_tooltip_tooltipview-TooltipView.html#member-position) with some sample positions that we use but developers could've implemented their own under different names. There's no way to tell what to do with them, for instance, they could've created a `.ck-tooltip_custom` and changing it to `.ck-tooltip_sw` will break the integration.
    *   I don't like this coupling of the `ToolbarView` and its items. It would be best if these 2 worked independently and the toolbar never touched the internals of its items, especially when they were set by the features.
        *   In theory, we could implement `ToolbarView#position = 'auto'` that would permit the toolbar to take the control over the position of the item's tooltip. But then we would need two observable properties: one to tell whether the position can be auto-adjusted by the `ToolbarView`, then another that is bound straight to CSS.
    *   This all asks for the `ToolbarViewItem` interface if the `ToolbarView` is to touch the internals of its items. Otherwise, there will be mess.
*   I also though we could handle it in plain CSS e.g. by overriding the look of the tooltip (via `:last-child`). However, because the DOM structure of the toolbar is not simple (there's an internal container for children, and a separate one for the grouped items dropdown), a simple selector will not handle many cases. For instance, a last item of the toolbar is not `:last-child` when the grouped items dropdown is visible.

```diff

diff --git a/packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/tooltip/tooltip.css b/packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/tooltip/tooltip.css
index 331d4c8176..9d43d417c0 100644
--- a/packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/tooltip/tooltip.css
+++ b/packages/ckeditor5-theme-lark/theme/ckeditor5-ui/components/tooltip/tooltip.css
@@ -7,11 +7,10 @@
 
 :root {
 	--ck-tooltip-arrow-size: 5px;
+	--ck-tooltip-arrow-offset: 5px;
 }
 
 .ck.ck-tooltip {
-	left: 50%;
-
 	/*
 	 * Prevent blurry tooltips in LoDPI environments.
 	 * See https://github.com/ckeditor/ckeditor5/issues/1802.
@@ -34,7 +33,6 @@
 		padding: var(--ck-spacing-small) var(--ck-spacing-medium);
 		background: var(--ck-color-tooltip-background);
 		position: relative;
-		left: -50%;
 
 		&::after {
 			/*
@@ -44,40 +42,88 @@
 			 */
 			transition: opacity .2s ease-in-out .2s;
 			border-style: solid;
-			left: 50%;
 		}
 	}
 
 	/**
-	 * A class once applied displays the tooltip south of the element.
+	 * Classes that contol the position of the tooltip:
+	 *
+	 *            [element]
+	 *                ^
+	 *          +-----------+
+	 *          |  Tooltip  |                .ck-tooltip_s
+	 *          +-----------+
 	 *
-	 *       [element]
-	 *           ^
+	 *            [element]
+	 *                ^
 	 *     +-----------+
-	 *     |  Tooltip  |
+	 *     |  Tooltip  |                    .ck-tooltip_sw
 	 *     +-----------+
+	 *
+	 *            [element]
+	 *                ^
+	 *              +-----------+
+	 *              |  Tooltip  |           .ck-tooltip_se
+	 *              +-----------+
+	 *
+	 *          +-----------+
+	 *          |  Tooltip  |               .ck-tooltip_n
+	 *          +-----------+
+	 *                V
+	 *            [element]
 	 */
-	&.ck-tooltip_s {
+
+	&.ck-tooltip_s,
+	&.ck-tooltip_n {
+		left: 50%;
+
+		& .ck-tooltip__text {
+			left: -50%;
+
+			&::after {
+				left: 50%;
+			}
+		}
+	}
+
+	&.ck-tooltip_s,
+	&.ck-tooltip_sw,
+	&.ck-tooltip_se {
 		bottom: calc(-1 * var(--ck-tooltip-arrow-size));
 		transform: translateY( 100% );
 
 		& .ck-tooltip__text::after {
-			top: calc(-1 * var(--ck-tooltip-arrow-size));
+			top: calc(-1 * var(--ck-tooltip-arrow-size) + 1px);
 			transform: translateX( -50% );
 			border-color: transparent transparent var(--ck-color-tooltip-background) transparent;
 			border-width: 0 var(--ck-tooltip-arrow-size) var(--ck-tooltip-arrow-size) var(--ck-tooltip-arrow-size);
 		}
 	}
 
-	/**
-	 * A class once applied displays the tooltip north of the element.
-	 *
-	 *     +-----------+
-	 *     |  Tooltip  |
-	 *     +-----------+
-	 *           V
-	 *       [element]
-	 */
+	&.ck-tooltip_sw {
+		right: calc(50% - 2 * var(--ck-tooltip-arrow-offset));
+
+		& .ck-tooltip__text {
+			right: 0;
+
+			&::after {
+				right: 0;
+			}
+		}
+	}
+
+	&.ck-tooltip_se {
+		left: calc(50% - 2 * var(--ck-tooltip-arrow-offset));
+
+		& .ck-tooltip__text {
+			left: 0;
+
+			&::after {
+				left: calc(2 * var(--ck-tooltip-arrow-offset));
+			}
+		}
+	}
+
 	&.ck-tooltip_n {
 		top: calc(-1 * var(--ck-tooltip-arrow-size));
 		transform: translateY( -100% );
diff --git a/packages/ckeditor5-ui/src/toolbar/toolbarview.js b/packages/ckeditor5-ui/src/toolbar/toolbarview.js
index 7c8fc5e657..41ad4da84e 100644
--- a/packages/ckeditor5-ui/src/toolbar/toolbarview.js
+++ b/packages/ckeditor5-ui/src/toolbar/toolbarview.js
@@ -798,7 +798,10 @@ class DynamicGrouping {
 
 		// Make sure the dropdown never sticks out to the left/right. It should be under the main toolbar.
 		// (https://github.com/ckeditor/ckeditor5/issues/5608)
-		dropdown.panelPosition = locale.uiLanguageDirection === 'ltr' ? 'sw' : 'se';
+		//
+		// Make sure the dropdown tooltip does not cause body overflow (and scroll).
+		// (https://github.com/ckeditor/ckeditor5/issues/7327)
+		dropdown.panelPosition = dropdown.buttonView.tooltipPosition = locale.uiLanguageDirection === 'ltr' ? 'sw' : 'se';
 
 		addToolbarToDropdown( dropdown, [] );
 
```

---

BTW: We may have missed this because MacOS has this preference that hides the scrollbar in certain situations. I had to change it to reproduce the issue.

![](https://user-images.githubusercontent.com/1099479/83408026-34c65080-a412-11ea-939f-374adf4da229.png)

**Comment by o-alquimista** [comment]
How do I set the position of the tooltip of that specific grouped items dropdown to work around the issue the way @oleq did?

I've tried `editor.ui.view.toolbar.items`, but it doesn't include that one.

**Comment by oleq** [comment]
@o-alquimista FYI we're going to address this in #8655.

**Comment by o-alquimista** [comment]
I'm using version 25.0.0 now and, although the "show more items" tooltip is no longer overflowing the editor, there is still some horizontal overflow caused by CKEditor. Are you aware of this issue?

### With CKEditor:
![Captura de tela de 2021-02-19 14-04-16](https://user-images.githubusercontent.com/25424263/108536722-8756de00-72bb-11eb-87f3-4597e273eaf7.png)

### Without CKEditor:
![Captura de tela de 2021-02-19 14-04-32](https://user-images.githubusercontent.com/25424263/108536787-99d11780-72bb-11eb-8bb1-a55f79aefe24.png)

**Comment by archonic** [comment]
I've hit the same issue. I don't even know what element inside the toolbar is pushing it over. It doesn't appear to be any menus or tooltips. The discrepancy is 76px. This is what my toolbar has to look like to avoid the scrollbar:

![image](https://user-images.githubusercontent.com/588846/145695875-d0e6f3f5-85d2-4fb2-b3dd-7c9b032ca05f.png)

The scrollbar still appears when it's right about to collapse another toolbar item.

**Comment by archonic** [comment]
Still present in 31.1.0. Pretty hard to make a good decoupled editor experience with this bug present.

**Comment by SamuelHassine** [comment]
Still present in latest version. Hitting the same bug here.

**Comment by Soullighter** [comment]
Same bug present
